### ISSUE TITLE
USER STORY: Home Page

### ISSUE THREAD

**Issue by MoniPar** [MoniPar/reclaimed-treasures#11]
As a **User**, I can **land on the homepage of the site**, so that **I can learn more about the business and the types of products they sell**.

**Acceptance Criteria**

1. Website's url directs user to the homepage.
2. The homepage has a clear overview of what the site is about.

**Tasks**

- [x] Create the home view code 
- [x] Extend the home view template from the base template
- [x] Connect up the urls
