### ISSUE TITLE
USER STORY: Navigation

### ISSUE THREAD

**Issue by MoniPar** [MoniPar/reclaimed-treasures#12]
As a **User**, I can **view the logo and the links in the navigation bar**, so that **I can easily navigate to other pages of the site**.

**Acceptance Criteria**

1. The header is displayed at the top across all pages of the website.
2. The main header displays the logo, links, search bar, account and shopping basket icons.
3. Links to the other pages of the site can be easily accessed by all users.
4. Hamburger button for mobile toggles navbar links.

**Tasks**

- [x] Design a logo for the website 
- [x] Add a header with the logo and navigation links
- [x] Use Bootstrap 4 to create the responsive navbar
- [x] Link up FontAwesome for the search bar, account and basket

**Comment by MoniPar** [comment]
Logo text needs to be replaced by an image
