### ISSUE TITLE
USER STORY: Footer

### ISSUE THREAD

**Issue by MoniPar** [MoniPar/reclaimed-treasures#13]
As a **User**, I can **access contact details, social and developer links across all pages**, so that **I can follow/contact the business owner and the website creator**.

**Acceptance Criteria**

1. The footer is displayed at the bottom of the page across all pages of the website.
2. Contact details and social links are clearly displayed on all screen sizes.
3. Social links and privacy policy open in a new tab.
4. Copyright, date and link to website's creator profile is included at the bottom.
5. Contact link and Newsletter signup form are included at the top.

**Tasks**

- [x] Add footer to the base template 
- [x] Use Bootstrap 4 and custom css to create the footer
- [x] Add information and links to social media
- [x] Generate and add link to privacy statement
- [x] Allocate a space for the contact link and the newsletter signup form.
