### ISSUE TITLE
USER STORY: Call to Action

### ISSUE THREAD

**Issue by MoniPar** [MoniPar/reclaimed-treasures#14]
As a **business owner**, I can **have a banner with a CTA clearly visible on the landing page**, so that **users are encouraged to access the shop and view/buy products**.

**Acceptance Criteria**

1. A hero image that draws the eye and gives the user a visual representation of the artist's designs.
2. An overlay with text which encapsulates what the business is about.
3. A visible Shop Now button which will link to the Shop/Products page.

**Tasks**

- [x] Design a banner which represents some of the handmade designs and products in the shop 
- [x] Come up with the text for the overlay 
- [x] Write responsive code for the above

**Comment by MoniPar** [comment]
Needs a better image and styling
