### ISSUE TITLE
USER STORY: About section

### ISSUE THREAD

**Issue by MoniPar** [MoniPar/reclaimed-treasures#15]
As a **User**, I can **read about the business**, so that **I can decide if I want to purchase from them or not**.

**Acceptance Criteria**

1. A short section about the products.
2. A short section about the process.
3. A link to more information which will lead to the About page.

**Tasks**

- [x] Write the content 
- [x] Get and optimise an image of the artist
- [x] Code the section

**Comment by MoniPar** [comment]
Decided to go with 3 cards describing what the shop is about instead.
