### ISSUE TITLE
USER STORY: Products section

### ISSUE THREAD

**Issue by MoniPar** [MoniPar/reclaimed-treasures#16]
As a **business owner**, I can **display thumbnails with links of some of my products on the landing page**, so that **users are encouraged to click on them and view/buy more products**.

**Acceptance Criteria**

1. A Products section which displays at least three categories of products.
2. Each category is displayed on a card with name, image and a button that links to the shop.

**Tasks**

- [ ] Choose and optimise images to display 
- [ ] Create card and button link
- [ ] Make section responsive on all screen sizes

**Comment by MoniPar** [comment]
Will be added as a future feature because of time restrictions
