### ISSUE TITLE
USER STORY: Contact Form

### ISSUE THREAD

**Issue by MoniPar** [MoniPar/reclaimed-treasures#17]
As a **User**, I can **quickly write a message to the business owner using the contact form**, so that **I can ask questions or give feedback**.

**Acceptance Criteria**

1. Contact Page displays a hero image with a heading inviting users to get in touch.
2. Some text with information about why should users get in touch is displayed.
3. Contact information including; phone number, email and social links are also displayed here.
4. A Contact form with fields for Subject, Name, Email, Phone No and Message box are also included here.
5. User is alerted to any missing information when they try to submit the form.
6. When form is valid, user is directed to a Thank you page with a short message. 
7. Form information is recorded in the DB.
8. Shop owner receives an email with Subject, email address and message from the user.

**Tasks**

- [x] Create the Contact app
- [x] Add to INSTALLED_APPS and connect the URLs
- [x] Create and register the Contact model to the Admin site
- [x] Create the form
- [x] Create the contact.html template
- [x] Define the view and call its url

**Comment by MoniPar** [comment]
Added sending message as email functionality in order to help business owner to reply to messages directly from her business email account.
