### ISSUE TITLE
USER STORY: Newsletter

### ISSUE THREAD

**Issue by MoniPar** [MoniPar/reclaimed-treasures#18]
As a **User**, I can **sign up to the newsletter**, so that **I keep updated on the latest products, offers and pop up stalls**.

**Acceptance Criteria**

1. A Newsletter Email Signup Form is displayed on the footer.
2. When user submits email address, a success message is displayed below the field.
3. Email address is recorded on the Mailchimp account.

**Tasks**

- [x] Create a div for the newsletter signup form in the footer
- [x] Set up the business's newsletter and generate the HTML code using Mailchimp services
- [x] Add HTMl code, CSS & JS links, styles and scripts to the project's base.html template
