### ISSUE TITLE
USER STORY: Social Authentication

### ISSUE THREAD

**Issue by MoniPar** [MoniPar/reclaimed-treasures#19]
As a **User**, I can **connect with my social media account**, so that **I can easily create an account**.

**Acceptance Criteria**

1. User can register using their Facebook account.
2. 
3. 

**Tasks**

- [ ] Add facebook provider to INSTALLED_APPS
- [ ] Configure settings with SOCIALACCCOUNT_PROVIDERS
- [ ] Sign up for API client on Facebook and get client id and API secret
[ ]
