### ISSUE TITLE
USER STORY: Create the Django project and first app

### ISSUE THREAD

**Issue by MoniPar** [MoniPar/reclaimed-treasures#2]
As a **developer**, I can **create the Django project and home app**, so that **I can set up the database and initiate development**.

**Acceptance Criteria**

1.  Successful creation of the Django project directory.
2.  Successful creation of the Home app.
3.  The basic skeleton project is up and running.

**Tasks**

- [x] Create the Django project 
- [x] Create the Home app
- [x] Add it to the list of INSTALLED_APPS
- [x] Migrate the changes to the database
