### ISSUE TITLE
USER STORY: Setting up the online shop

### ISSUE THREAD

**Issue by MoniPar** [MoniPar/reclaimed-treasures#20]
As a **Shop Owner**, I can **use the Admin interface to add, update, view and delete products**, so that **I can populate the online shop**.

**Acceptance Criteria**

1. The ability to add, update, view and delete categories in the admin panel.
2. The ability to add products and their relative information and images via the admin panel.
3. The ability to view a list of products, update and delete specific products via the admin panel.

**Tasks**

- [x] Create the products app 
- [x] Add it to INSTALLED_APPS 
- [x] Create the Category model
- [x] Create the Product model
- [x] Install pillow and migrate
- [x] Register the models in the admin
- [x] Add categories and some products via the admin panel
