### ISSUE TITLE
USER STORY:  View Products

### ISSUE THREAD

**Issue by MoniPar** [MoniPar/reclaimed-treasures#24]
As a **Customer**, I can **view a list of products**, so that **I can select some to purchase**.

**Acceptance Criteria**

1. The Customer is able to see a list of products in the Shop/Products page.
2. Each product card displays an image, name, price, category, pattern, rating and link
3. The Customer is able to view a specific category of products.
4. The Customer is able to quickly identify deals and new products. 

**Tasks**

- [x] Create the view 
- [x] Connect up the URLs 
- [x] Create the products template
