### ISSUE TITLE
USER STORY: Search and Filter Products

### ISSUE THREAD

**Issue by MoniPar** [MoniPar/reclaimed-treasures#26]
As a **Customer**, I can **search for a specific product or view a category of products**, so that **I can quickly find products I'm interested in**.

**Acceptance Criteria**

1. Customer is able to search for a product by name.
2. Customer is able to search for a product by other keywords that are found in the description of the products.
3. Customer is able to see what they've searched for and the number of results.
4. Customer can return back to the shop page using the link at the front of the product count.
5. Customer is able to see which category they have selected.

**Tasks**

- [x] Add the action url to the base template  
- [x] Modify shop view by checking if 'q' is in request.GET and set it equal to query
- [x] Use Q to construct the search queries and pass them to the filter method, then return to the context
- [x] Pass the category query parameters in the templates
- [x] Modify the shop view by checking if categories is in request.GET, split it into a list and filter the products
- [x] Filter all categories to match the ones in the list from the URL
- [x] Return the list to the context
