### ISSUE TITLE
USER STORY: Basket Access

### ISSUE THREAD

**Issue by MoniPar** [MoniPar/reclaimed-treasures#29]
As a **customer**, I can **access my basket**, so that **I can review items before I purchase them**.

**Acceptance Criteria**

1. Customer is able to access the basket on different screen sizes via the main navigation.
2. Customer who have added products to their basket will be able to see the products listed.
3. Customers who have not yet added any products will be able to see some text and a link back to the shop.

**Tasks**

- [x] Create the basket app and add to INSTALLED_APPS
- [x] Create the basket view
- [x] Create the templates directory and the basket template
- [x] Wire up the URLs
