### ISSUE TITLE
USER STORY: Context Processor

### ISSUE THREAD

**Issue by MoniPar** [MoniPar/reclaimed-treasures#30]
As a **developer**, I can **create a context processor**, so that **I can access the basket related variables from other apps in my project**.

**Acceptance Criteria**

1. The basket contents can be accessed in any templates across the entire site.

**Tasks**

- [x] Create the context.py file in the basket app
- [x] Add it to the context processor in settings.py
- [x] Add the delivery logic and calculation
- [x] Count and calculate the total cost of the items in the basket 
- [x] Update context.py to make the basket's contents available across the entire site
