### ISSUE TITLE
USER STORY: Add items & total cost

### ISSUE THREAD

**Issue by MoniPar** [MoniPar/reclaimed-treasures#31]
As a **customer**, I can **add items and identify their total cost in the basket**, so that **I know how much I'm spending**.

**Acceptance Criteria**

1. The customer can add items to their basket.
2. The customer can easily return back to the shop page from the basket.
3. The customer can view the subtotal and total sum of the items in their basket

**Tasks**

- [x] Add form to product_detail template
- [x] Write the view to handle the form
- [x] Create the URL for the view
- [x] Update the basket template to render out the list of items and the total cost + delivery charges
- [x] Add Back to shop and Checkout buttons
