### ISSUE TITLE
USER STORY: Quantity Selector

### ISSUE THREAD

**Issue by MoniPar** [MoniPar/reclaimed-treasures#32]
As a **developer**, I can **add functionality with the plus (+) and minus (-) buttons to the quantity selector**, so that **the user has a better experience adding products to their basket on mobile**.

**Acceptance Criteria**

1. The customer is able to use buttons to increase/decrease the quantity of each product they would like to order from the product_detail page.
2. The customer is able to use buttons to increase/decrease the quantity of each product they would like to order from their basket page.
3. Using buttons the customer is only able to add up to 3 items on products that are Made to Order from the product detail page.
4. Using buttons the customer is only able to add up to 3 items on products that are Made to Order from the basket page.

**Tasks**

- [x] Use Bootstrap's built-in input group append and input group prepend classes to add the buttons in the product_detail template
- [x] Write the JS to handle updating the input box
- [x] Write the JS to handle enabling and disabling the buttons based on the value of the input they're controlling
- [x] Add the Quantity selector form group for the items in the basket page and include the script at the bottom
