### ISSUE TITLE
USER STORY: Updating and Removing Items

### ISSUE THREAD

**Issue by MoniPar** [MoniPar/reclaimed-treasures#33]
As a **Customer**, I can **update the quantity of each item in my basket**, so that **I can easily make changes to my order before checkout**.

**Acceptance Criteria**

1. The Customer is able to update the quantity of each individual item in their basket via the update link.
2. The Customer is able to remove a product from their basket via the remove link.
3. The Customer is able to see the subtotal for the amount of each product in their basket.

**Tasks**

- [x] Create links in the basket template for updating and removing items
- [x] Write the JS to handle these two elements being clicked
- [x] Write the views to handle updating item quantities and removing them from the basket
- [x] Connect up the URLs for the views
- [x] Add the action URL to the form in the basket template
- [x] Create a bag tools module to handle the subtotal calculation function and register it as a template filter
- [x] Load the filter in the basket template
