### ISSUE TITLE
USER STORY: Toasts

### ISSUE THREAD

**Issue by MoniPar** [MoniPar/reclaimed-treasures#34]
As a **User**, I can **see real-time notifications as I interact with the website**, so that **I can have a better experience**.

**Acceptance Criteria**

1. The User is provided with neat and clear notifications when using functional features of the site.
2. The notifications are designed to display the result of the user's interaction.

**Tasks**

- [x] Create messages toast templates using Bootstrap's toats
- [x] Create conditional messages logging in base template
- [x] Edit basket views by adding messages to the 'add', 'update', 'remove' views
- [x] Add Boostrap JS to show the toast
- [x] Configure settings.py to store messages in the session 
- [x] Customise toasts to match the site and to show a little preview of the basket
