### ISSUE TITLE
USER STORY: Checkout App

### ISSUE THREAD

**Issue by MoniPar** [MoniPar/reclaimed-treasures#35]
As a **developer**, I can **create a checkout app**, so that **I can implement functionality for the customer to enter required information and view their delivery cost, order and grand total**.

**Acceptance Criteria**

1. The Oder and OrderLIneItem models are created in models.py.
2. A signals.py file is created.
3. The order form can be accessed in the Admin panel.

**Tasks**

- [x] Create checkout app and add it to INSTALLED_APPS
- [x] Create the Order and OrderLineItem models and methods 
- [x] Migrate and Register the models to the Admin
- [x] Create a signals.py file and add functions to call the update and delete methods
- [x] Override the ready method in apps.py
- [x] Create the checkout form
