### ISSUE TITLE
USER STORY:  Checkout page

### ISSUE THREAD

**Issue by MoniPar** [MoniPar/reclaimed-treasures#36]
As a **Customer**, I can **confirm my items and total cost in the checkout page**, so that **I can continue to enter the required information to complete my order**.

**Acceptance Criteria**

1. Customer is able to view the items they want to order.
2. Customer is able to view the order total, delivery cost and grand total.
3. Customer is easily able to enter their information & delivery/billing address in the required fields.
4. Customer can go back to the basket page to add, replace or remove items.

**Tasks**

- [x] Create the checkout view
- [x] Connect the URLs
- [x] Create the checkout template
- [x] Install django-crispy-forms, add to requirements and configure settings
- [x] Link up basket.html
