### ISSUE TITLE
USER STORY: Setup Stripe credit card input field

### ISSUE THREAD

**Issue by MoniPar** [MoniPar/reclaimed-treasures#37]
As a **Developer**, I can **use Stripe Elements**, so that **I can setup a secure payment system to the online shop**.

**Acceptance Criteria**

1. A payment field which matches all other fields is displayed on the checkout page.
2. The payment field requires a card number, expiration date and CVC.
3. An invalid card number turns red 

**Tasks**

- [ ] Setup Stripe Elements: Add script to base.html
- [ ] Add the public and client secret test key to the context in the checkout view
- [ ] Make sure to keep public key secret - add to env.py and call from settings then call from checkout view
- [ ] Write the JS in an external file to get the keys and to set up Stripe and create the card element
- [ ] Add it to the checkout template
