### ISSUE TITLE
USER STORY: Payment system basic functionality

### ISSUE THREAD

**Issue by MoniPar** [MoniPar/reclaimed-treasures#38]
As a **Customer**, I can **easily enter my payment information**, so that **I can checkout quickly and efficiently**.

**Acceptance Criteria**

1. The form is submitted by entering the test card number and any other digits for the rest.
2. A successful payment notification is displayed in Stripe/Developers/Events

**Tasks**

- [x] Add a listener on the card element for the change event in the external JS file
- [x] Get the basket total in the Checkout view
- [x] Install Stripe and add it to requirements
- [x] Configure Stripe variables in settings.py, codeAnywhere and Heroku
- [x] Create the payment intent in the Checkout view
- [x] Add a listener to the payment form's submit event
- [x] Test basic functionality
