### ISSUE TITLE
USER STORY: Checkout success logic

### ISSUE THREAD

**Issue by MoniPar** [MoniPar/reclaimed-treasures#39]
As a **Customer**, I can **view an order confirmation after checkout**, so that **I can confirm that my order was successful**.

**Acceptance Criteria**

1. The Customer is able to see their products and totals in the checkout page.
2. The Customer is alerted to enter required fields in the checkout form.
3. The Customer is able to checkout using the test card number from Stripe, the form should be submitted.
4. The Customer is then redirected to the Checkout success page.
5. Stripe/Developers/Events shows payment intent succeeded.
6. The order is created with all the expected lineitems and the order in the Admin panel.

**Tasks**

- [ ] Add handling for the POST method in the Checkout view 
- [ ] Create the Checkout success view 
- [ ] Wire up the URL
- [ ] Create the Checkout success template
- [ ] Test the payment flow is working properly
