### ISSUE TITLE
USER STORY: AWS Bucket Setup

### ISSUE THREAD

**Issue by MoniPar** [MoniPar/reclaimed-treasures#4]
As a **developer**, I can **set up and connect the project to AWS S3**, so that **I can upload images and static files to a persistent file store**.

**Acceptance Criteria**

1. Successful creation of the S3 bucket and the media and static directories within the bucket.
2. Successful connection between Django and AWS S3.
3. Successful connection between AWS S3 and Heroku.

**Tasks**

- [x] Create a new S3 bucket in AWS S3 services 
- [x] Configure the newly created bucket to enable static website hosting and permissions for access with Heroku
- [x] Create a security policy for the bucket and configure to allow full access
- [x] Create AWS Groups, Policies and Users
- [x] Install the boto3 and django-storages packages and add to INSTALLED_APPS
- [x] Configure settings.py to connect Django to S3
- [x] Add required config vars to Heroku
- [x] Add cache control
- [x] Add Media files to S3

**Comment by MoniPar** [comment]
Still need to add cache control and media files to S3

**Comment by MoniPar** [comment]
Completed and deployed successfully.  Setup real email too which was tested by sending a message through the contact form.  Open issue: Bug - Contact form email_from #49
