### ISSUE TITLE
USER STORY: Stripe Webhooks

### ISSUE THREAD

**Issue by MoniPar** [MoniPar/reclaimed-treasures#40]
As a **Developer**, I can **make sure that customers can confidently provide the information required safely and securely**, so that **they can have a positive experience on the site**.

**Acceptance Criteria**

1. A loading modal informs the user that the transaction is being processed.
2. The payment intent is successfully created and stripe prints "Created order in webhook".
3. The order is submitted to the database.
4. The product stock is decremented.
5. The basket is cleared.

**Tasks**

- [x] Create a loading modal and add js to the handle for submit
- [x] Test using extra authentication test card
- [x] Add webhook event handlers and the webhook function
- [x] Add Stripe Webhook Secret to settings and CodeAnywhere and Heroku
- [x] Create data caching from checkout form
- [x] Add the webhook handler for payment intent succeeded
- [x] Test functionality
