### ISSUE TITLE
USER STORY: Product Stock

### ISSUE THREAD

**Issue by MoniPar** [MoniPar/reclaimed-treasures#41]
As a **Developer**, I can **decrement stock on payment success**, so that **I can add functionality when item becomes out of stock**.

**Acceptance Criteria**

1. Product stock is displayed on the product detail page.
2. Product stock is decremented every time a customer makes a purchase. 
3. When product stock is 0, the text changes to 'Made to Order'.
4. When product is marked as 'Made to Order', customer is only allowed to order up to 3 of the product.

**Tasks**

- [ ] Write the code to decrement the stock depending on the quantity purchased in the checkout view
- [ ] Edit the quantity input fields on product_detail and basket templates to allow only a maximum of 3 on Made to order products
- [ ] Edit the JS to disable the increment button when input is 3  
[ ] 
[ ]

**Comment by MoniPar** [comment]
Bug:  The customer can order up to 3 if the product is already made to order but they cannot order more than what is in stock even if they are within the 3 max limit on made to order.
