### ISSUE TITLE
USER STORY: User Profile

### ISSUE THREAD

**Issue by MoniPar** [MoniPar/reclaimed-treasures#42]
As a **Registered Customer**, I can **have a personal user profile**, so that **I can save my payment info and view my order history and confirmations**.

**Acceptance Criteria**

1.  A User Profile is automatically created for the user upon registration.
2.  The registered user is able to access their profile through the link in the navbar.
3.  The registered user is able to logout from their profile through the link in the navbar.

**Tasks**

- [x] Create the profile app and add to INSTALLED_APPS
- [x] Create the User Profile Model and a method for creating / updating the user profile
- [x] Add signal and attach the User Profile to the Order Model then migrate
- [x] Setup the view and template and connect the URLs
- [x] Customise allauth templates 
- [x] Test and update the links in the base.html
- [x] Get the current user in the view and return it to the template
