### ISSUE TITLE
USER STORY: Update User Profile

### ISSUE THREAD

**Issue by MoniPar** [MoniPar/reclaimed-treasures#43]
As a **Customer**, I can **edit personal information on my profile**, so that **I can use the correct details when processing future orders**.

**Acceptance Criteria**

1. The Customer is able to update their personal information in their profile.
2. The Customer is able to see a history of their order in their profile.
3. (The information saved in the profile can be retrieved in the checkout form, if the user checks the save info checkbox).

**Tasks**

- [x] Create the form for the user to update their default delivery info
- [x] Import the form to the view, populate it with user's current profile info and return it to the template
- [x] Update the template to show their order history
- [x] Add the post handler to the profile view
- [x] Add the order history to the template and create a view for the order history, connect the URLs
- [x] Add the User Profile to the Checkout Success view
