### ISSUE TITLE
USER STORY: Email Confirmation

### ISSUE THREAD

**Issue by MoniPar** [MoniPar/reclaimed-treasures#44]
As a **Customer**, I can **receive an email confirmation after checking out**, so that **I can keep the confirmation of the transaction for my records**.

**Acceptance Criteria**

1. The Customer is able to their order history in their profile even if the checkout success page fails.
2. The Customer will receive a confirmation email of their order.

**Tasks**

- [x] Update the payment intent succeeded method to get the user's information if authenticated and to make sure an order is created for anonymous users
- [x] Test if payment succeeds and order is created in admin when the form fails to submit
- [x] Create the confirmation email subject and body text files 
- [x] Add a send confirmation email method in the Stripe webhook handler
- [x] Add the DEFAULT_FROM_EMAIL to settings.py
- [x] Test functionality by logging in a confirmation email in the terminal after checkout
