### ISSUE TITLE
USER STORY: Product Review

### ISSUE THREAD

**Issue by MoniPar** [MoniPar/reclaimed-treasures#46]
As a **Customer**, I can **check products' ratings and reviews and submit my own**, so that **I can make up my mind if I want to purchase the product and provide feedback on products purchased**.

**Acceptance Criteria**

1. Users are able to see ratings for products in the shop.
2. Users are able to see reviews, if any, on each product's detail page.
3. Registered Users are able to rate and submit reviews on products.
4. Registered Customers are able to rate and submit reviews of products they have purchased.

**Tasks**

- [x] Create the Product Review model 
- [x] Create the Product Review form
- [x] Add the code to display the reviews in the product detail template
- [x] Write the method to get and post the rating and review in the product detail view 
- [x] Create a model function to get the total rating for the product
