### ISSUE TITLE
USER STORY: About Page

### ISSUE THREAD

**Issue by MoniPar** [MoniPar/reclaimed-treasures#47]
As a **User**, I can **navigate to the About page**, so that **I can learn more about the shop owner and her business**.

**Acceptance Criteria**

1. User can easily navigate to the About Page from the Navigation (and from the about section on the homepage).
2. An image of the shop owner is displayed here.
3. Information about the shop owner and her craft are displayed here.
4. A CTA that leads to the shop.
5. A card with a link to the contact page.

**Tasks**

- [x] Create the view
- [x] Create the template
- [x] Connect up the urls
- [x] Write the about content and add the images
- [x] Add section on commissions with link to contact page
- [x] Add CTA
