### ISSUE TITLE
USER STORY: Preparation and first deployment

### ISSUE THREAD

**Issue by MoniPar** [MoniPar/reclaimed-treasures#5]
As a **developer**, I can **configure settings in the Django project**, so that **the project is deployed successfully**.

**Acceptance Criteria**

1.  Django knows where the templates are stored in both development and production.
2.  Django knows where the project is being hosted.
3.  Successful first deployment.

**Tasks**

- [x] Set up the templates directory in setttings.py 
- [x] Add the Heroku host name into ALLOWED_HOSTS
- [x] Create the media, static and templates directories
- [x] Create a Procfile
- [x] Deploy
