### ISSUE TITLE
USER STORY: Social Media Marketing (organic)

### ISSUE THREAD

**Issue by MoniPar** [MoniPar/reclaimed-treasures#50]
As a **Business Owner**, I can **have my Business Facebook page linked with my website**, so that **I can connect and interact with my customers directly and potentially extend my reach through posts and other content creation**.

**Acceptance Criteria**

1. Website users can access the Business Facebook page through the link in the footer and on the contact page.
2. Facebook users can access the Website through the link on the Facebook business account and posts.
3. Facebook page has relevant information about the business.

**Tasks**

- [ ] Create a Facebook business page with the name of the Business
- [ ] Add contact information, business hours and website link
- [ ] Add profile picture and cover photo 
- [ ] Choose action button
- [ ] Create first post with link to Website
- [ ] Add the facebook page link to the website's footer and contact page
