### ISSUE TITLE
USER STORY: SEO Implementations

### ISSUE THREAD

**Issue by MoniPar** [MoniPar/reclaimed-treasures#51]
As a **Developer**, I can **add metadata, a sitemap  and robots.txt file**, so that **the website can be found and ranked by search engines**.

**Acceptance Criteria**

1. The relevant keywords and descriptions are included in the main pages meta tags.
2. A sitemap.xml file is included in the project's root folder.
3. A robots.txt file is included in the project's root folder.

**Tasks**

- [x] Add meta tags to base.html and other main html pages with relevant keywords
- [x] Generate a sitemap.xml and add it to the root folder 
- [x] Add a robots.txt file
