### ISSUE TITLE
USER STORY: Error Pages

### ISSUE THREAD

**Issue by MoniPar** [MoniPar/reclaimed-treasures#55]
As a **Developer**, I can **build custom error pages**, so that **the user remains on the site and has a way to get back to the homepage or access navigation**.

**Acceptance Criteria**

1. Have a custom error pages with styles that match the website.
2. These pages define the error and display a button to bring the user back to the homepage.

**Tasks**

- [x] Create the handler function in the main project directory views
- [x] Create the templates in the root templates directory 
- [x] Configure the handler's URL
- [x] Test in production
