### ISSUE TITLE
USER STORY: Registration

### ISSUE THREAD

**Issue by MoniPar** [MoniPar/reclaimed-treasures#7]
As a **user**, I can **register for an account**, so that **I have access to other features of the website**.

**Acceptance Criteria**

1. A user can register for an account using a username, email and password.

**Tasks**

- [x] Install Django Allauth and add to requirements.txt 
- [x] Add to installed apps and add authentication backends
- [x] Add 'accounts' to project urls
- [x] Update the domain of the default site in the Admin panel for future use (social media authentication)
